/**
* @file person.h
* @author AEDA T4GE
* @title Class Person and Subclasses Stundent and Tutor
* @brief Classes used to store information of a Student or a Tutor
*/
#pragma once


#include <vector>
#include <string>
#include "exceptions.h"
#include "course.h"
#include "Date.h"

using namespace std;

typedef unsigned int uint;

class Person;
class Tutor;
class Student;
class Course;
class Date;

class Person {
protected:
	string code, name;
public:
	/**
	*@brief Constructor of pure virtual class Person
	*@param code of the person related to the department
	*@param name of the person
	*/
	Person(string code, string name);

	/**
	*@brief virtual fuction that returns the name of a Person
	*@return string with the name
	*/
	virtual string get_name() const = 0;

	/**
	*@brief virtual fuction that returns the code of a Person
	*@return string with the code
	*/
	virtual string get_code() const = 0;

	/**
	*@brief virtual fuction that sets the Name of a Person
	*/
	virtual void setName(string newName) = 0;
};

class Tutor : public Person {
private:

public:
	//se der tempo mudar isto para privado
	vector<Student *> students;

	/**
	*@brief Constructor of the class Tutor
	*@param code of the tutor generated by the program itself or read from textfile
	*@param name of the tutor
	*/
	Tutor(string code, string name);

	/**
	*@brief virtual fuction that returns the name of a Tutor
	*@return string with the name
	*/
	string get_name() const;

	/**
	*@brief virtual fuction that returns the code of a Tutor
	*@return string with the code
	*/
	string get_code() const;

	/**
	*@brief Changes the Tutor's name
	*@param newName Tutor's new name
	*/
	void setName(string newName);

	/**
	*@brief Tutor has a vector of students mentored by him, adds a student to this vector
	*@param x Pointer to the student to add
	*/
	void add_student(Student* x);

	/**
	*@brief Operator < to see who's the tutor who has less students to mentor
	*@param t Tutor to compare with
	*/
	bool operator< (const Tutor &t) const;

	/**
	@brief Operator << for Tutor
	@param os ostream&
	@param tutor Tutor object to send to outstream
	*/
	friend ostream& operator<<(ostream &os, const Tutor &tutor);
};

class Student : public Person {
private:
	bool interrupted, finished;
	string email, status, tutor;
	double approved_credits, credits;
	vector<Course *> enrolled_courses;
	vector<Course *> approved_courses;
	vector<Date *> enrolled_dates;
	vector<Date *> approved_dates;
public:
	/**
	*@brief Constructor of the class Student
	*@param code of the student generated by the program itself or read from textfile
	*@param name of the student
	*@param email of the student
	*@param status of the student (if it's "Trabalhador Estudante", "Ordinário" etc.)
	*@param code of the mentor (tutor) if already assigned
	*/
	Student(string code, string name, string email, string status, string tutor);

	/**
	*@brief Constructor of the class Student
	*@param code Student's code generated automatically or read from a text file
	*@param name Student's name
	*@param email Student's e-mail
	*@param status Student's status ("Trabalhador Estudante", "Ordinário")
	*@param interrupted True if student has interrupted the degree, false otherwise
	*@param finished True if student has terminated the degree, false otherwise
	*/
	Student(string code, string name, string email, string status, bool interrupted, bool finished);

	/**
	*@brief Get a Student's name
	*@return Student's name as a string
	*/
	string get_name() const;

	/**
	*@brief Get a Student's code
	*@return Student's code as a string
	*/
	string get_code() const;

	/**
	*@brief Get a student's e-mail
	*@return Student's e-mail as a string
	*/
	string get_email() const;

	/**
	*@brief Get a student's status
	*@return Student's status as a string
	*/
	string get_status() const;

	/**
	*@brief Get a student's tutor's code
	*@return Student's tutor's code as a string
	*/
	string get_tutor() const;
	
	/**
	*@brief access the data-member "interrupted"
	*@return value of the data-member "interrupted"
	*/
	bool hasInterrupted() const;

	/**
	*@brief access the data-member "finished"
	*@return value of the data-member "finished"
	*/
	bool hasFinished() const;

	/**
	*@brief Function that returns a vector with the courses the student is enrolled
	*@return vector<Course *> with student enrolled courses
	*/
	vector<Course *> get_enrol_courses() const;

	/**
	*@brief Function that returns a vector with the courses the student has been approved at
	*@return vector<Course *> with student approved courses
	*/
	vector<Course *> get_approv_courses() const;

	/**
	*@brief Function that returns a vector with the dates at which the student enrolled at a course (organized respectively with the vector of enrolled courses)
	*@return vector<Date *> with the date at which the student enrolled at a course
	*/
	vector<Date *> get_enrol_dates() const;

	/**
	*@brief Function that returns a vector with the dates at which the student was approved at a course (organized respectively with the vector of enrolled courses)
	*@return vector<Date *> with the date at which the student was approved at a course
	*/
	vector<Date *> get_approv_dates() const;

	/**
	*@brief returns the number of approved credits
	*@return number of credits
	*/
	double get_appcredits() const;

	/**
	*@brief returns the number of credits assigned
	*@return number of credits assigned for
	*/
	double get_credits() const;

	/**
	*@brief sets the status of the student to active
	*/
	void resumeDegree();

	/**
	*@brief Changes the Student's name
	*@param newName Student's new name
	*/
	void setName(string newName);

	/**
	*@brief Changes the Student's e-mail
	*@param newEmail Student's new e-mail
	*/
	void setEmail(string newEmail);

	/**
	*@brief Changes the Student's status
	*@param newStatus Student's new status
	*/
	void setStatus(string newStatus);

	/**
	*@brief If a course is complered add credits of the respective course to approved credits of the student
	*@param x number of credits to add
	*/
	void add_approved_credits(double x);

	/**
	*@brief If a course is enrolled add credits of the respective course to credits of the student
	*@param x number of credits to add
	*/
	void add_credits(double x);

	/**
	*@brief Assigns a tutor to the student
	*@param tut Pointer to the Tutor to assign
	*/
	void assign_tutor(Tutor *tut);
	
	/**
	*@brief Enrols a student in a course
	*@param course Course to enrol in
	*@param date Date of the student's enrolment in the course
	*/
	void enroll_course(Course *course, Date *date);

	/**
	*@brief If student passed the course removes it from the enrolled courses and goes to approved courses
	*@param course course to assign
	*/
	void approve_course(Course *course, Date *date);

	/**
	@brief Operator << for Student
	@param os ostream&
	@param s Student object to use the operator
	*/
	friend ostream& operator<<(ostream &os, const Student &s);
};